config/routes.rb
Pfc::Application.routes.draw do
  ## Dashboard

  root :to => 'dashboard#index'
  get 'dashboard' => redirect('/'), :as => 'dashboard'

  ## Login & Signup

  get  'login'  => 'sessions#new',     :as => 'login'
  post 'login'  => 'sessions#create'
  get  'logout' => 'sessions#destroy', :as => 'logout'

  resource :session

  get  'signup' => 'users#new', :as => 'signup'
  post 'signup' => 'users#create'

  ## Accounts, Transactions, Analytics, & Uploads

  resources :accounts do
    resources :transactions, :controller => 'txactions' do
      member do
        put :undelete
      end
    end

    collection do
      get  :search
      post :enable
      post :trigger_updates
    end

    member do
      get :financial_institution_site
    end
  end

  # TODO: Fix this hack.
  get '/transactions/rational(.:format)' => 'rational_txactions#index'
  get '/transactions/rational/*tags(.:format)', :to => 'rational_txactions#index'

  resources :transactions, :controller => 'txactions' do
    member do
      put :undelete
      get :on_select_merchant
      get :transfer_selector
      get :merchant_list_checks
    end
  end

  resources :tags
  resources :attachments
  resources :account_merchant_tag_stats
  resources :targets
  resources :trends
  resources :uploads do
    collection do
      match :choose
      get   :manual
    end
  end

  # TODO: use resource routing for this
  post '/targets/delete' => 'targets#destroy'

  resources :merchants do
    collection do
      get :my,     :to => 'merchants#user_index'
      get :public, :to => 'merchants#public_index'
    end
  end

  resources :financial_insts, :path => 'financial-institutions'

  ## Member Data Snapshots

  resource  :snapshot

  ## Big Rock Candy Mountain Passthrough

  match '/data/transactions/*uri(.:format)',            :to => 'brcm#transactions'
  match '/data/investment-transactions/*uri(.:format)', :to => 'brcm#transactions'
  match '/data/*uri(.:format)',                         :to => 'brcm#passthrough'

  ## User Profile & Preferences

  resource :profile
  resource :preferences, :controller => 'user_preferences'
  resource :user do
    post :edit_filter_tags, :to => 'users#edit_filter_tags'
    get :password, :to => 'users#edit_password'
    put :password, :to => 'users#update_password'
    get :download_data
    get :delete_membership
  end

  ## Server-Side Uploader

  resources :credentials, :controller => 'account_creds' do
    resources :jobs, :controller => 'ssu_jobs'
  end

  ## Help & About

  get 'page/contribute', :as => :contribute, :to => 'page#contribute'
  get 'page/what',       :as => :what,       :to => 'page#what'
end

app/controllers/financial_insts_controller.rb
class FinancialInstsController < ApplicationController
  before_filter :check_authentication
  before_filter :check_for_admin, :only => [:edit, :update, :destroy, :unapproved, :confirm_merge, :merge]

  # GET /financial-institutions
  # GET /financial-institutions.xml
  # GET /financial_insts/list?format=xml
  def index
    @financial_insts = FinancialInst.for_user(current_user).order('name ASC')
    respond_to do |format|
      format.html { check_for_admin }     # index.html.erb    ## admin-only. stupid stupid stupid
      format.xml  { render :layout => false } # index.xml.builder
      format.json { render :layout => false } # index.json.erb
    end
  end

  # GET /financial-institutions/unapproved
  def unapproved
    @financial_insts = FinancialInst.paginated_find_all_unapproved(params[:page], :per_page => 1000)
  end

  # GET /financial-institutions/new
  def new
    get_countries
    @financial_inst = FinancialInst.new(:name => params[:name], :country_id => current_user.country_id)
  end

  # POST /financial-institutions
  def create
    # only allow users to set name, homepage_url, and country
    fi_params = (params[:financial_inst] || {}).slice(:name, :homepage_url, :country_id)
    @financial_inst = FinancialInst.new(fi_params.update(:creating_user_id => current_user.id, :approved => false))
    if @financial_inst.save
      # continue on with the upload process
      flash[:fi_confirmation] = "Your financial institution has been added."
      redirect_to manual_uploads_path(:fi => @financial_inst)
    else
      get_countries
      render :action => "new"
    end
  end

  # GET /financial-institutions/1/edit
  # GET /financial-institutions/us-000238/edit
  def edit
    @financial_inst = FinancialInst.find_for_user(params[:id], current_user) || raise(ActiveRecord::RecordNotFound)
  end

  # PUT /financial-institutions/1
  # PUT /financial-institutions/us-000238
  def update
    @financial_inst = FinancialInst.find_for_user(params[:id], current_user) || raise(ActiveRecord::RecordNotFound)
    if @financial_inst.update_attributes(params[:financial_inst])
      redirect_to(financial_inst_url(@financial_inst))
    else
      render :action => "edit"
    end
  end

  # GET /financial-institutions/1
  # GET /financial-institutions/us-000238
  # GET /financial-institutions/1.xml
  # GET /financial_insts/1?format=xml
  def show
    @financial_inst = FinancialInst.find_for_user(params[:id], @user || current_user) || raise(ActiveRecord::RecordNotFound)

    respond_to do |format|
      format.html {
        raise(ActiveRecord::RecordNotFound) unless check_for_admin
        generate_fi_stats; render :action => 'show' # show.html.erb
      }
      format.xml { render :xml => @financial_inst }
    end
  end


  def generate_fi_stats
    @recent_jobs    = @financial_inst.
                        all_ssu_jobs.
                        latest(10).
                        map(&:presenter)
    @recent_signups = @financial_inst.
                        all_ssu_jobs.
                        signups.
                        limit(10).
                        order('created_at DESC').
                        map(&:presenter)

    ## FIXME: This is really inefficient, need to add a real by_fi filter
    activity_30d = SsuJobs::Activity.new(30.days.ago, Time.now)
    activity_30d.wesabe_id = @financial_inst.wesabe_id
    activity_30d.summarize!()
    @fi_stats_30d = activity_30d.get_stats_for_wesabe_id(@financial_inst.wesabe_id)
    return unless @fi_stats_30d

    @fi_okay = []
    @fi_fail = []
    @fi_auth = []
    @fi_pend = []
    @fi_all  = []

    ## FIXME: Sorting shouldn't happen here!
    @fi_stats_30d.slot_stats.sort_by {|_| _.slot }.each do |slot_stat|
      @fi_okay << [slot_stat.slot*1000, slot_stat.sum_okay]
      @fi_fail << [slot_stat.slot*1000, slot_stat.sum_fail]
      @fi_auth << [slot_stat.slot*1000, slot_stat.sum_auth]
      @fi_pend << [slot_stat.slot*1000, slot_stat.sum_pending]
      @fi_all  << [slot_stat.slot*1000, slot_stat.sum_jobs]
    end

    activity_07d = SsuJobs::Activity.new(
      Chronic.parse('7 days ago'),
      Chronic.parse('today')
    )
    activity_07d.wesabe_id = @financial_inst.wesabe_id
    activity_07d.summarize!
    @fi_stats_07d = activity_07d.get_stats_for_wesabe_id(@financial_inst.wesabe_id)
  end
  hide_action :generate_fi_stats

  # DELETE /financial-institutions/1
  # DELETE /financial-institutions/us-000238
  def destroy
    @financial_inst = FinancialInst.find_for_user(params[:id], current_user) || raise(ActiveRecord::RecordNotFound)
    if @financial_inst.destroy
      redirect_to unapproved_financial_insts_url
    else
      render :action => "destroy"
    end
  end

  # GET /financial-institutions/:id/confirm_merge
  def confirm_merge
    @financial_inst = FinancialInst.find_by_wesabe_id(params[:id])
    @target_fi = FinancialInst.find(params[:target_fi_id])
    redirect_to financial_insts_url unless @financial_inst && @target_fi
  end

  # POST /financial-institutions/:id/merge
  def merge
    @financial_inst = FinancialInst.find_by_wesabe_id(params[:id])
    @target_fi = FinancialInst.find(params[:target_fi_id])
    @financial_inst.mapped_to_id = @target_fi.id
    FinancialInst.merge(@financial_inst.id, @financial_inst.mapped_to_id)
    redirect_to(financial_inst_url(@target_fi))
  end

private

  # Retrieves a list of countries for the select box on #new and #create.
  def get_countries
    @countries = Country.ids_and_names
  end

  def check_authentication
    if params[:job_guid]
      job = SsuJob.find_by_job_guid(params[:job_guid])
      if job && !job.expired? && (@user = User.find_by_id(params[:user_id]))
        return true
      else
        render :nothing => true, :status => 401
      end
    else
      super
    end
  end

end

app/helpers/financial_insts_helper.rb
module FinancialInstsHelper

  def fi_homepage_link(fi)
    if fi && !fi.homepage_url.to_s.blank?
      link_to(fi.homepage_url, fi.homepage_url, :target => "new")
    else
      "your bank's website"
    end
  end

end

app/views/financial_insts/confirm_merge.html.erb
<%- set_page_title "Confirm FI Merge" -%>

<%- content_for :header do -%>
  <style type="text/css">
    p { margin-left: 1em }
    h2 { margin-left: 1em; margin-top: 1em }
    div#merged_fi {float: left; width: 45%; margin: 2em, 0, 2em, 2em }
    div#merged_into_fi {float: right; width: 45%; margin: 2em, 2em, 2em, 0 }
    div#merged_fi, div#merged_into_fi {border: 1px dotted grey; padding: 1em;}
    div#submit {margin-top: 16em; margin-left: 2em}
  </style>
<%- end -%>

<div id="merged_fi">
  <h1>Merge this...</h1>
  <h2><%=h @financial_inst.name %></h2>
  <p>ID: <%=  @financial_inst.wesabe_id + " (" + @financial_inst.id.to_s + ")"  %></p>
  <p>Homepage: <%= @financial_inst.homepage_url ? auto_link(@financial_inst.homepage_url, :all, :target => '_blank') : 'n/a' %></p>
  <p>Login page: <%= @financial_inst.login_url ? auto_link(@financial_inst.login_url, :all, :target => '_blank') : 'n/a' %></p>
  <p>Number of accounts: <%=h @financial_inst.accounts.count %></p>
</div>

<div id="merged_into_fi">
  <h1>...into this.</h1>
  <h2><%=h @target_fi.name %></h2>
  <p>ID: <%=  @target_fi.wesabe_id + " (" + @target_fi.id.to_s + ")"  %></p>
  <p>Homepage: <%= @target_fi.homepage_url ? auto_link(@target_fi.homepage_url, :all, :target => '_blank') : 'n/a' %></p>
  <p>Login page: <%= @target_fi.login_url ? auto_link(@target_fi.login_url, :all, :target => '_blank') : 'n/a' %></p>
  <p>Number of accounts: <%=h @target_fi.accounts.count %></p>
</div>


<div id="submit">
  <%- form_tag(merge_financial_inst_url(:target_fi_id => @target_fi.id, :id => @financial_inst)) do -%>
    <%= submit_tag("Confirm Merge") %>
  <%- end -%>
</div>

app/views/financial_insts/destroy.html.erb
<h1>Can't delete this financial institution</h1>

<p><%=h @financial_inst.name %> has <%= pluralize(@financial_inst.accounts.count, "account") %>,
  and we think it'd be rude to delete it.</p>

app/views/financial_insts/edit.html.erb
<%- content_for :header do -%>
  <style type="text/css" media="screen">
    a.big-delete {
      background-color: #f00;
      font-weight: bold;
      padding: 5px, 5px, 5px, 5px;
      margin-top: 15px;
      text-align: center;
      color: #fff;
      width: 100%;
      display: block; }
    p img {
      float: none;
      margin: 0;
    }
  </style>
<%- end -%>

<%- set_page_title "Edit #{@financial_inst.name} (#{@financial_inst.wesabe_id})" -%>

<div class="top">
  <div class="right"></div>
</div>
<div class="middle">
  <div class="right">
    <h2>Edit '<%=h @financial_inst.name %>'</h2>

    <% form_for @financial_inst do |f| %>

      <%= f.error_messages %>

      <p><label for="financial_inst_name">Name</label><br/>
      <%= f.text_field :name %>
      <%= link_to image_tag('icon-google-tiny.gif'), "http://www.google.com/search?q=#{CGI.escape(@financial_inst.name)}", :target => '_blank' %></p>

      <p><label for="financial_inst_homepage_url">Homepage URL</label><br/>
      <%= f.text_field :homepage_url  %>
      <%= link_to_function image_tag('arrow-next.gif'), "window.open($F('financial_inst_homepage_url'))" %></p>

      <p><label for="financial_inst_login_url">Login URL</label><br/>
      <%= f.text_field :login_url  %>
      <%= link_to_function image_tag('arrow-next.gif'), "window.open($F('financial_inst_login_url'))" %></p>

      <p><label for="financial_inst_ofx_fid">OFX Fid</label><br/>
      <%= f.text_field :ofx_fid  %></p>

      <p><label for="financial_inst_ofx_org">OFX Org</label><br/>
      <%= f.text_field :ofx_org  %></p>

      <p><label for="financial_inst_ofx_brker">OFX Broker Id</label><br/>
      <%= f.text_field :ofx_broker  %></p>

      <p><label for="financial_inst_ofx_url">OFX URL</label><br/>
      <%= f.text_field :ofx_url  %></p>

      <p><label for="financial_inst_connection_type">Connection type: </label>
      <%= f.select :connection_type, FinancialInst.connection_type_options %></p>

      <p><label for="financial_inst_account_number_regex">Account Number Regex:</label>
      <%= f.text_field :account_number_regex %></p>

      <p><label for="financial_inst_ssu_support">SSU support?</label>
      <%= f.select :ssu_support, FinancialInst::SSUSupport.options_for_select  %></p>

      <p><label for="financial_inst_ofx_fee">OFX Fee?</label>
      <%= f.check_box :ofx_fee  %></p>

      <p><label for="financial_inst_featured">Show in "Popular Bank" list?</label>
      <%= f.check_box :featured  %></p>

      <p><label for="financial_inst_bad_balance">Bad Balance?</label>
      <%= f.check_box :bad_balance  %> <em>(Note: Enabling "Bad Balance" makes the balance of all accounts at this FI user editable.)</em></p>

      <p><label for="financial_inst_good_txid">Good Transaction IDs?</label>
      <%= f.check_box :good_txid  %> <em>(Note: Enabling "Good Transaction IDs" means that when matching transactions we trust the FI's transaction IDs.)</em></p>

      <p><label for="financial_inst_country_id">Country</label><br/>
      <%= f.select :country_id, Country.ids_and_names %></p>

      <p><label for="financial_inst_statement_date_format">Date Format</label><br/>
      <%= f.select :statement_date_format, FinancialInst.date_format_options %></p>

      <p><label for="financial_inst_help_text">Help Text</label><br/>
      <%= f.text_area :help_text, :size => '80x4' %></p>

      <p><label for="financial_inst_notes">Notes (not shown to non-admin users)</label><br/>
      <%= f.text_area :notes, :size => '80x4'  %></p>

      <p><label for="financial_inst_status">Status</label>
      <%= f.select :status, FinancialInst::Status.options_for_select  %></p>

      <p><%= f.submit "Save" %></p>

    <% end %>

    <br /><hr /><br />

    <% form_tag("confirm_merge", :method => :get) do %>
      <%- if @financial_inst.mapped_to_id -%>
          <h2>This FI is already merged to <%= @financial_inst.mapped_to_id %>.</h2>
      <%- end -%>
      <p>Merge into <%= select_tag("target_fi_id", options_for_select(FinancialInst.ids_and_names, @financial_inst.id.to_s)) %> <%= submit_tag "Sanity Check" %></p>
    <% end %><br />

    <p>
      <%= link_to "Delete", financial_inst_url(@financial_inst), :method => :delete, :confirm => "Are you sure you want to delete this FI?", :class => 'big-delete' %>
    </p>
  </div> <!-- middle right -->
</div> <!-- middle -->
<div class="bottom">
  <div class="right"></div>
</div>

app/views/financial_insts/index.html.erb
<h1>Financial Institutions</h1>

<style type="text/css">
table {
	border-collapse: collapse;
}

td, th {
	padding: 0.5em;
	border: 1px solid #CCC;
}

thead, tfoot {
	background-color: #DDD;
}

tr.rowodd {
	background-color: #FFF;
}

tr.roweven {
	background-color: #F2F2F2;
}

.sortcol {
	cursor: pointer;
	padding-right: 20px;
	background-repeat: no-repeat;
	background-position: right center;
}
.sortasc {
	background-color: #DDFFAC;
	background-image: url(/images/up.gif);
}
.sortdesc {
	background-color: #B9DDFF;
	background-image: url(/images/down.gif);
}
.nosort {
	cursor: default;
}
</style>

<table class="sortable">
  <thead>
    <tr>
      <th id="fi-table-id">ID</th>
      <th class="sortfirstdesc" id="fi-table-name">Name</th>
      <th id="fi-table-wesabe_id">Wesabe ID</th>
      <th id="fi-table-url">URL</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <td>ID</td>
      <td>Name</td>
      <td>Wesabe ID</td>
      <td>URL</td>
    </tr>
  </tfoot>
  <tbody>
    <% for financial_inst in @financial_insts %>
    <tr>
      <td><%= financial_inst.id %></td>
      <td><%= link_to(h(financial_inst.name), financial_inst_url(financial_inst)) %></td>
      <td><%= financial_inst.wesabe_id %></td>
      <td>
        <%= link_to_url financial_inst.url %>
      </td>
      <td><%= link_to "Edit", edit_financial_inst_url(financial_inst) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/financial_insts/index.json.erb
<%= @financial_insts.map(&:name).to_json.html_safe %>

app/views/financial_insts/new.html.erb
<% stylesheet "upload-accounts" %>
<% javascript 'wesabe/views/shared/form' %>

<style type="text/css" media="screen">
  #form_body form { float: left;}
</style>

<div id="three-col-center">
  <div class="two-column flat" id="upload-account">
    <div class="top"><div class="right"><div class="grip"></div></div></div>
    <div class="middle"><div class="right">
    <div class="content">
      <div class="module-header">
        <h4>Getting Started</h4>
      </div>
      <div id="upload-index">
        <!-- BEGIN steps -->
        <ul class="upload-steps">
          <li class="on">1. Find your bank</li>
          <li>2. Connect to your bank</li>
          <li>3. Select your accounts</li>
        </ul>
        <!-- END steps -->
        <div id="color_body">

          <div id="help">
              <h6>Keep track of your cash expenses&hellip;</h6>
              <a id="create-cash-account-button" class="button orange"><span>Create a Cash Account</span></a>
              <%= render :partial => "uploads/cash_account_form" %>
          </div>

<!-- BEGIN form_body --><div id="form_body">

<h6>Add Your Bank</h6>
  <% form_for @financial_inst do |f| %>
    <%= error_messages_for(:financial_inst).gsub("financial inst.", "financial institution.") %>
    <fieldset>
      <div class="field">
        <label for="financial_inst_name" class="field-title">Your Bank&rsquo;s Full Name</label>
        <%= f.text_field :name %>
      </div>

      <div class="field">
        <label for="financial_inst_homepage_url" class="field-title">Your Bank&rsquo;s Home Page</label>
        <%= f.text_field :homepage_url %>
      </div>

      <div class="field">
        <label for="financial_inst_country_id" class="field-title">Your Bank&rsquo;s Country</label>
        <%= f.select :country_id, @countries, {} %>
      </div>
      <a id="bank_next_on" class="button submit green"><span>Continue</span></a>
      <a class="button cancel gry" onclick="javascript:history.go(-1);"><span>Cancel</span></a>
  </fieldset>
  <%- end -%>
</div><!-- END form_body -->
<div class="clear">&nbsp;</div>
</div><!-- END color_body -->
        <div style="clear">&nbsp;</div>
      </div>
    </div>
  </div></div>
  <div class="bottom"><div class="right"></div></div>
  </div>
</div>