config/routes.rb
Pfc::Application.routes.draw do
  ## Dashboard

  root :to => 'dashboard#index'
  get 'dashboard' => redirect('/'), :as => 'dashboard'

  ## Login & Signup

  get  'login'  => 'sessions#new',     :as => 'login'
  post 'login'  => 'sessions#create'
  get  'logout' => 'sessions#destroy', :as => 'logout'

  resource :session

  get  'signup' => 'users#new', :as => 'signup'
  post 'signup' => 'users#create'

  ## Accounts, Transactions, Analytics, & Uploads

  resources :accounts do
    resources :transactions, :controller => 'txactions' do
      member do
        put :undelete
      end
    end

    collection do
      get  :search
      post :enable
      post :trigger_updates
    end

    member do
      get :financial_institution_site
    end
  end

  # TODO: Fix this hack.
  get '/transactions/rational(.:format)' => 'rational_txactions#index'
  get '/transactions/rational/*tags(.:format)', :to => 'rational_txactions#index'

  resources :transactions, :controller => 'txactions' do
    member do
      put :undelete
      get :on_select_merchant
      get :transfer_selector
      get :merchant_list_checks
    end
  end

  resources :tags
  resources :attachments
  resources :account_merchant_tag_stats
  resources :targets
  resources :trends
  resources :uploads do
    collection do
      match :choose
      get   :manual
    end
  end

  # TODO: use resource routing for this
  post '/targets/delete' => 'targets#destroy'

  resources :merchants do
    collection do
      get :my,     :to => 'merchants#user_index'
      get :public, :to => 'merchants#public_index'
    end
  end

  resources :financial_insts, :path => 'financial-institutions'

  ## Member Data Snapshots

  resource  :snapshot

  ## Big Rock Candy Mountain Passthrough

  match '/data/transactions/*uri(.:format)',            :to => 'brcm#transactions'
  match '/data/investment-transactions/*uri(.:format)', :to => 'brcm#transactions'
  match '/data/*uri(.:format)',                         :to => 'brcm#passthrough'

  ## User Profile & Preferences

  resource :profile
  resource :preferences, :controller => 'user_preferences'
  resource :user do
    post :edit_filter_tags, :to => 'users#edit_filter_tags'
    get :password, :to => 'users#edit_password'
    put :password, :to => 'users#update_password'
    get :download_data
    get :delete_membership
  end

  ## Server-Side Uploader

  resources :credentials, :controller => 'account_creds' do
    resources :jobs, :controller => 'ssu_jobs'
  end

  ## Help & About

  get 'page/contribute', :as => :contribute, :to => 'page#contribute'
  get 'page/what',       :as => :what,       :to => 'page#what'
end

app/controllers/api/upload_controller.rb
class Api::UploadController < ApplicationController
  include Api::UploadHelper

  layout nil

  before_filter :check_basic_auth_credentials

  # exception we throw if we get a request that's too large
  class RequestSizeExceeded < Exception; end
  class UnsupportedUploader < Exception; end

  # return config file with user accounts
  def config
    # check api version
    api_version = get_api_version(request.user_agent)
    return render(:action => 'error/version') unless compatible_version?(api_version)

    # KLUDGE: throw an exception if the version is 1.09/Mac because Jay released debug code
    if request.user_agent =~ /1\.0\.9.*?darwin/i
      return render(:action => 'error/unsupported_uploader_version')
    end

     # update last api login
    @user.last_api_login = Time.now
    @user.save

    @accounts = @user.active_accounts
  end

  # method to upload a set of transaction data
  def statement
    if request.post?
      begin
        Importer.import_request(@user, request, @account_cred_id)
      rescue RequestSizeExceeded
        return render_text('', '413 Request Entity Too Large')
      rescue Importer::UnsupportedStatementType
        return render(:action => 'error/unsupported_statement_type')
      rescue Exception => e
        logger.error([e.message, *e.backtrace].join("\n"))
        render(:action => 'error/import_failed')
      end
    end
  end

private

  def check_basic_auth_credentials
    if params[:job_guid] && params[:user_id]
      job = SsuJob.find_by_job_guid(params[:job_guid])
      if job && !job.expired? && (@user = User.find_by_id(params[:user_id]))
        @account_cred_id = job.account_cred_id
        set_current_user(@user)
      else
        render :text => "Invalid job: Access denied.", :status => 401
      end
    else
      @user = authenticate_or_request_with_http_basic "Wesabe Upload API" do |username, password|
        if user = User.authenticate(username, password)
          set_current_user(user)
        end
        user
      end
    end
  rescue Authentication::LoginThrottle::UserThrottleError
    render(
      :text => 'Too many failed login attempts. This account is temporarily disabled. Please try again later.',
      :status => :forbidden,
      :layout => false
    )
    return false
  end

end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_filter :check_authentication
  before_filter :only_allow_html, :only => [:new, :manual, :ssu]
  before_filter :require_ac, :only => [:error, :security]

  # FIXME: we should not be declaring stylesheets in the controller
  stylesheet 'upload-accounts'

  WEB_UPLOADER_CLIENT_NAME = 'Wesabe-WebUploader'
  WEB_UPLOADER_CLIENT_VERSION = '1.1'

  def index
    if params[:account_id]
      if @account = current_user.account(params[:account_id])
        @uploads = @account.uploads.reject {|u| u.txaction_count_for_account(@account) == 0}
        @last_balance = @account.last_balance
        return render
      end
    end
    redirect_to root_url # if all else fails, just send the user home
  end

  # show the file associated with this upload
  def destroy
    if upload = Upload.find_by_guid(params[:id])
      if upload.owned_by_user?(current_user)
        upload.destroy_for_account(current_user.account(params[:account_id]))
      end
    end
    render :nothing => true
  end

  def new
    @featured_fis = FinancialInst.find_all_by_featured(true, :order => "name")
  end

  def choose
    return unless financial_inst

    if ssu_enabled? && financial_inst.ssu_support?(current_user)
      # If possible, send users to SSU
      @path = new_credential_path(:fi => financial_inst)
    end

    # Worst case (or by request), manual uploads
    if params[:upload_type] != "manual" && @path
      redirect_to @path
    else
      redirect_to manual_uploads_path(:fi => financial_inst)
    end
  end

  def manual
    @financial_inst = financial_inst
    @need_more_info = params[:need_more_info]
    @show_form = "display:none;" unless flash[:error]
  end

  def error
    respond_to do |format|
      format.html
    end
  end

  # The select action now takes three parameters to help make working with it
  # easier. An example:
  #
  #     new_accounts=1&old_accounts=6&fi=us-000238
  #
  # This will pretend that SSU found one new account, six old accounts, and that
  # the bank was Bank of America. All params are optional, but there must be one
  # or both of new_accounts and old_accounts.
  def select
    if Rails.development? && (params[:old_accounts] || params[:new_accounts])
      @fi = params[:fi] ?
        FinancialInst.find_for_user(params[:fi], current_user) :
        FinancialInst.first(:conditions => ['wesabe_id like ?', 'us-%'])
      @new_accounts, @old_accounts = [], []
      params[:new_accounts].to_i.times {|i| @new_accounts << Account.create_sample}
      params[:old_accounts].to_i.times {|i| @old_accounts << Account.create_sample}
    else
      require_ac
      @accounts = @ac.accounts
      @new_accounts, @old_accounts = @accounts.partition do |account|
        account.newly_created_by?(@ac) || account.disabled?
      end
    end
  end

  def create
    @need_more_info = false
    referer = internal_referer || {}

    if params[:statement]
      unless file_provided?(params[:statement])
        flash[:error] = { :message => "Please upload a bank/creditcard statement." }
        params.delete(:statement)
        return redirect_to(referer.reverse_merge(params))
      end

      upload_params = {
        :user => current_user,
        :account_type => params[:account_type],
        :statement => params[:statement].read,
        :client_name => WEB_UPLOADER_CLIENT_NAME,
        :client_version => WEB_UPLOADER_CLIENT_VERSION,
        :client_platform_id => ClientPlatform.find_or_create_by_name(request.user_agent).id
      }
      upload_params.update(:account => account) if account
      upload_params.update(:financial_inst_id => financial_inst.id, :account_name => financial_inst.name) if financial_inst

      begin
        upload = Upload.generate(upload_params)
        flash[:error] = nil # not sure why we'd have to do this; but the error sticks around otherwise
      rescue MakeOFX2::TimeoutError => e
        flash[:error] = {:message => "There was a problem processing the statement you uploaded. Please <a href='#{new_support_request_url}'>contact support</a> for help." }
        return redirect_to(referer.reverse_merge(params))
      # FIXME: have the following return more information to the user about what kind of document they just uploaded (e.g. sorry, we don't accept PDF files)
      rescue MakeOFX2::AbstractException => e
        flash[:error] = {:message => "We couldn't parse the statement you uploaded. We only understand OFX, QFX, OFC, or QIF " +
        "files at the moment, and sometimes even those can throw us a curveball. Please try another format." }
        return redirect_to(referer.reverse_merge(params))
      end

      # get the statement format; if OFX, convert it and we're done; if QIF, we need to get
      # account type, number, and balance
      if @account || upload.original_format =~ /^(OFX|OFC)/
        begin
          Importer.import(upload)
        rescue Importer::UnsupportedStatementType
          logger.warn("unsupported statement type")
          flash[:error] = { :message => "We didn't recognize the account type in the statement you uploaded. We currently only " +
          "support bank or credit card statements. We don't yet support investment accounts (if this " +
          "is not an investment account, we probably had trouble parsing your statement." }
          return redirect_to(referer.reverse_merge(params))
        rescue Importer::XMLParseException => e
          subject = "fixofx failed importing #{upload.original_format} statement from #{financial_inst ? financial_inst.name : 'UNKNOWN'} (#{financial_inst ? financial_inst.wesabe_id : 'UNKNOWN'}) with #{e.class}"
          logger.error(subject + ': ' + e.message)
          flash[:error] = {:message => "We couldn't parse the statement you uploaded." }
          return redirect_to(referer.reverse_merge(params))
        end
      else # QIF upload...need to get more info
        # store the upload data in a temp file and go get more info
        FileUtils.mkdir_p(ApiEnv::PATH[:upload_temp_dir])
        tempfile = File.open(TempfilePath.generate('upload', ApiEnv::PATH[:upload_temp_dir]), "w")
        Marshal.dump(upload, tempfile)
        tempfile.close
        session[:upload_tempfile] = tempfile.path
        params[:statement] = nil
        return redirect_to(referer.reverse_merge(params).update(:need_more_info => true))
      end
    elsif params[:balance] # we're returning from collecting the QIF data
      if params[:account_number].blank? || (params[:account_number].size > 4)
        flash[:error] = "Please enter the last 4 digits of the account number."
        flash[:error_for] = 'account_number'
      elsif params[:balance].blank?
        flash[:error] = "Please enter a balance."
        flash[:error_for] = 'balance'
      elsif params[:account_type].blank?
        flash[:error] = "Please select an account type."
        flash[:error_for] = 'account_type'
      end
      if flash[:error]
        return redirect_to(referer.reverse_merge(params).update(:need_more_info => true))
      end

      # retrieve the upload from the temp file
      upload = nil
      begin
        tempfile = File.open(session[:upload_tempfile])
        Upload # make sure Upload is loaded for Marshal
        upload = Marshal.load(tempfile)
      rescue Exception => ex
        logger.error("Exception unmarshalling upload temp file (#{session[:upload_tempfile]}): " +
          ex.message + "\n    " + ex.backtrace.join("\n    "))
      ensure
        File.delete(session[:upload_tempfile]) if session[:upload_tempfile] && File.exist?(session[:upload_tempfile])
        session[:upload_tempfile] = nil
      end

      unless upload
        logger.error("upload has gone missing!")
        flash[:error] = "There was a problem processing your uploaded statement. Please try again."
        return redirect_to(referer)
      end

      upload.account_type = params['account_type']
      upload.account_number = params['account_number']
      upload.balance = params[:balance]
      upload.convert_to_ofx2 # reconvert to ofx

      Importer.import(upload)
    end

    if !@need_more_info && !flash[:error] && (upload && !upload.accounts.blank?)
      return redirect_to(account_path(upload.accounts.first.id_for_user))
    else
      return redirect_to(accounts_path)
    end
  end

private

  def financial_inst
    @financial_inst ||= begin
      account && account.financial_inst ||
        FinancialInst.find_for_user(params[:fi_name] || params[:fi], current_user).tap do |fi|
          redirect_to new_upload_path if fi.nil?
        end
    end
  end

  def account
    @account ||= current_user.active_account_by_uri_for_user(params.delete(:account_uri))
  end

  def require_ac
    @ac = current_user.find_by_cred_guid(params[:cred])
    @fi = @ac.financial_inst if @ac
    redirect_to new_upload_path unless @ac
  end
end

app/helpers/api/upload_helper.rb
module Api::UploadHelper
  include Api::Constants

  # extract api version from User-Agent string
  def get_api_version(user_agent)
    logger.debug("user agent: #{user_agent}")
    match = user_agent.match(%r{Wesabe-API/(\S+)})
    return match ? match[1] : ""
  end

  def get_desktop_uploader_version(user_agent)
    match = user_agent.match(%r{Wesabe-Uploader/(\S+)})
    return match ? match[1] : ""
  end

  # return true if the uploader version is compatible with the api
  def compatible_version?(version)
    return version.version_to_i >= Api::Constants::OLDEST_SUPPORTED_API_VERSION.version_to_i
  end

  # return true if the uploader version is the most recent (use >= just in case the
  # CURRENT_UPLOADER_VERSION constant falls behind the actual current uploader version
  def most_recent_version?(version)
    return version.version_to_i >= Api::Constants::CURRENT_UPLOADER_VERSION.version_to_i
  end

end

app/helpers/uploads_helper.rb
module UploadsHelper
  def txaction_date_range(upload)
    min = upload.txactions.minimum(:date_posted)
    max = upload.txactions.maximum(:date_posted)
    return 'n/a' if min.nil? || max.nil?

    result = very_short_friendly_date(min)
    result << '..' << very_short_friendly_date(max) unless min.to_date == max.to_date
    return result
  end

  # Renders the Javascript required to redirect the browser to FI#new including
  # the FI name the user typed in.
  def new_bank_js_link(input_element_id)
    %Q{
      var bank_name = $('##{input_element_id}').val();
      if(bank_name != ''){
        window.location.href = '#{new_financial_inst_url}?name=' + encodeURIComponent(bank_name);
      } else {
        alert('Try typing in the first few letters of your bank or credit card. If you don\\'t see it, then click this link to add it.');
      }
    }.gsub(/[\s]+/m, " ")
  end

  def login_field_for(field)
    content_tag(:label, "#{field[:label]} #{content_tag(:span, "", :class => "error_message", :style => "display:none")}", :for => field[:key], :class => 'field-title') +
    case field[:type]
    when "password"
      password_field_tag(field[:key], "", :class => "medium_text_field cred_field")
    when "state"
      %{<select class="cred_field state_select" id="#{field[:key]}" name="#{field[:key]}">\n} +
        %{<option value="">-- choose state --</option>} +
        options_for_select(Constants::STATES) + %{\n</select>}
    else # "text"
      text_field_tag(field[:key], "", :class => "medium_text_field cred_field initial-focus", :autocomplete => "off")
    end
  end

  def help_text_for(fi)
    case text = fi.help_text(:ssu)
    when /<[a-z]+(\s[^>]*)?>/
      text
    else
      auto_link text.
        sub(/^(.*?(?:[\.\!\?](?=[ <])|[\.\!\?]$|$))/) { "<strong>#{$1}</strong>" }.
        gsub("\n", "<br/>\n"),
      :all, :target => '_blank'
    end
  end
end

app/views/uploads/_cash_account_form.html.erb
<div id="create-cash-account-form" class="edit-dialog" style="display:none">
  <%= form_tag(accounts_path, :id => 'account_upload') do -%>
    <%= hidden_field_tag 'account_type', 'Cash' %>
    <label for="name" class="cash">Account Name</label>
    <p><%= text_field_tag 'name', 'Cash Account', :style=>"width:140px" %></p>
    <label for="currency" class="cash">Currency</label>
     <p><%= select_tag('currency',
            options_for_select(currency_short_options_for_select,
            current_user.default_currency.name)) %>
    </p>
    <a class="button submit green"><span>Create</span></a>
    <a class="button cancel gry"><span>Cancel</span></a>
  <%- end -%>
</div>

app/views/uploads/_failed_error.html.erb
<div id="second_error">
  <h4class="error_title" style="color:#999;">Sorry, that didn&rsquo;t work either.</h4>
  <%= link_to image_tag("banner-try_another.png", :alt => "Try to connect another way. We’ll tell you what to do on the next page."), manual_uploads_path(:id => @fi) %>
  <%= link_to content_tag(:span, "Continue"), manual_upload_path(:id => @fi), :class => 'button green' %>
</div>

app/views/uploads/_retry_error.html.erb
<div id="first_error" style="color:#999;">
  <h4 class="error_title" style="color:#999;">We&rsquo;re sorry, we aren&rsquo;t able to connect to your bank right now.</h4>
  <%= link_to image_tag("banner-try_again.png", :alt => "Try again. Double-check your username and password. Also, make sure you have an online account with this bank."), destroy_account_cred_url(@ac, :second_try => true), :method => :delete %>
  <%= link_to content_tag(:span, "Continue"), destroy_account_cred_url(@ac, :second_try => true), :method => :delete, :class => 'button green' %>
      <p class="large"><br/><br/><em>You can always try <%=h @fi.name %> again later.</em></p>
</div>

app/views/uploads/error.html.erb
<% @tab = 'accounts' -%>
<% set_page_title = "Automatic Uploader", "Connection Error" %>

<%- content_for :header do -%>
  <style type="text/css">
    div#errorExplanation {width:90%; margin:0 auto 1em; font-size:90%; background: #fff; padding-top: 0}
  </style>
<%- end -%>


<div id="three-col-center">
  <div class="two-column flat" id="upload-account">
    <div class="top"><div class="right"><div class="grip"></div></div></div>
    <div class="middle"><div class="right">
    <div class="content">
      <div class="module-header">
        <h4>Getting Started</h4>
      </div>
      <!-- BEGIN upload index -->
      <div id="upload-index">
        <!-- BEGIN steps -->
        <ul class="upload-steps">
          <li class="off">1. <%= link_to "Find", new_upload_path %> your bank</li>
          <li class="on">2. Connect to your bank</li>
          <li>3. Select your accounts</li>
        </ul>
        <!-- END steps -->

        <div id="color_body">
          <!-- BEGIN help -->
          <div id="help">
             <h6 class="color_title">Other ways to Upload&hellip;</h6>
             <ul >
               <li class="manual"><%= link_to "Manual Uploads", manual_upload_path(:fi => @fi) %></li>
             </ul>
             <h6 class="color_title">Why Wouldn&rsquo;t It Work?</h6>
              <ol class="sidebar_list">
                <li>Typo while entering username/password?</li>
                <li>Bank website unavailable?</li>
              </ol>
          </div>
          <!-- END help -->

          <div id="form_body">
            <h3><%= @fi.name %></h3>

            <%- unless params[:second_try] -%>
            <%= render :partial => "retry_error" %>
            <%- else -%>
            <%= render :partial => "failed_error" %>
            <%- end -%>

          </div><!-- END form_body -->

          <div class="clear">&nbsp;</div>
        </div><!-- END color_body -->
        <div class="clear">&nbsp;</div>
      </div><!-- END upload index -->
    </div>
    </div></div>
    <div class="bottom"><div class="right"></div></div>
    </div>
  </div>
</div>

app/views/uploads/index.html.erb
<% content_for :header do -%>
<style type="text/css">
table#uploads { font-size: 90% }
table#uploads th,
table#uploads td { padding: 0 0.5em }
table#uploads td {border-bottom: 1px dashed #999}
h1 a:link, h1 a:visited { color:#2645BF !important; }
</style>
<% end -%>

<h1>Uploads for <%= @account ? link_to(h(@account.name), account_url(@account)) : 'All Accounts' %></h1>

<% if @uploads.empty? -%>
  <em>There are no uploads with transactions in this account.</em>
<% else -%>
<table id="uploads">
  <tr>
    <th>Date</th><th>Client</th><th>Transactions</th>
  </tr>
<% for upload in @uploads -%>
  <tr class="row">
    <td><%= short_friendly_date(upload.created_at) %></td>
    <td><%= h upload.client_name %> <%= h upload.client_version %></td>
    <td>
      <%= link_to "#{upload.txaction_count_for_account(@account)} (<small>#{txaction_date_range(upload)}</small>)",
            url_for(:controller => 'accounts', :action => 'show', :id => @account, :upload_id => upload.guid) %>
    </td>
    <td>
      <a class="delete button" onclick="confirmDelete.show(this, '<%= upload_path(:id => upload.guid, :account_id => @account) %>');">delete</a>
    </td>
  </tr>
<% end -%>
</table>
<% end -%>

<% content_for :footer do -%>
<script type="text/javascript">
// delete upload confirmation dialog
var confirmDelete = {
  dialog: null,
  init: function() {
    this.dialog = new YAHOO.widget.SimpleDialog("confirm_delete",
     { width: "400px",
       fixedcenter: true,
       visible: false,
       modal: !$.browser.msie, // modal in IE sucks
       draggable: false,
       close: false,
       constraintoviewport: true,
       text: '<b>Permanently</b> delete this upload and associated transactions?',
       buttons: [ { text: 'Yes, <b>delete this upload</b>',
                    handler: function(){ confirmDelete.okHandler() } },
                  { text: 'Cancel',
                    handler: function(){ confirmDelete.cancelHandler() } } ]
     });
     this.dialog.render("container");
  },
  okHandler: function() {
    this.dialog.hide();
    $(this.deleteButton).parents("tr").fadeOut("slow");
    $.post(this.url,{_method:'delete'}); // this is how Rails fakes a DELETE
  },
  cancelHandler: function() { this.dialog.hide(); },
  show: function(element, url) {
    this.deleteButton = element;
    this.url = url;
    this.dialog.show();
  }
};
$(function(){confirmDelete.init();});
</script>
<% end -%>

app/views/uploads/select.html.erb
<% @tab = 'accounts' -%>
<% set_page_title "Automatic Uploader", "Enable Accounts" %>

<% javascript 'wesabe/views/shared/form' %>

<div id="three-col-center">
  <div class="two-column flat" id="upload-account">
    <div class="top"><div class="right"><div class="grip"></div></div></div>
    <div class="middle"><div class="right">
      <div class="content">
        <div class="module-header">
        <h4>Getting Started</h4>
      </div>
        <div id="upload-index">
          <!-- BEGIN steps -->
          <ul class="upload-steps">
            <li>1. Find your bank</li>
            <li>2. Connect to your bank</li>
            <li class="on">3. Select your accounts</li>
          </ul>
          <!-- END steps -->
          <div id="color_body">
            <div id="help">
               <h6 class="color_title">Other ways to Upload&hellip;</h6>
               <ul>
                 <li class="manual"><%= link_to "Manual Uploads", manual_upload_path(:fi => @fi) %></li>
               </ul>
            </div><!-- END help -->
            <div id="form_body">
              <h3><%=h @fi.name %>
              <%= link_to truncate(@fi.url, 45), @fi.url, :target=>"new", :class=>"fi_url" %></h3>

              <%- form_tag enable_accounts_path do -%>
              <p class="note_wide">
              <%- if @new_accounts.any? -%>
              <%- if @new_accounts.size == 1 -%>
              <strong>We found one new account.</strong>
              Rename it if you like, and uncheck it if you don&rsquo;t want to add it.
              <%- else -%>
              <strong>We found new accounts.</strong>
              Rename each if you like, and uncheck those you don&rsquo;t want to add.
              <%- end # if @new_accounts.size == 1 -%>
              <%- else -%>
              <%- if @old_accounts.size == 1 -%>
              <strong>We found one existing account.</strong>
              Rename it if you like.
              <%- else -%>
              <strong>We found these existing accounts.</strong>
              Rename them if you like.
              <%- end # if @old_accounts.size == 1 -%>
              <%- end # if @new_accounts.any? -%>
              </p><!-- END note -->

              <ul id="bank_accounts">
          <%- @new_accounts.each do |account| -%>
          <li class="new_account">
            <span class="check_box"><%= check_box_tag "accounts[#{account.to_param}][enabled]", true, true %></span>
            <%= text_field_tag "accounts[#{account.to_param}][name]", account.name, :class => "medium_text_field account_name" %>
            <%= text_field_tag "accounts[#{account.to_param}][balance]", number_to_currency(account.balance, :unit => account.currency.unit), :class => "medium_text_field disabled balance", :disabled => true %>
          </li>
          <%- end -%>

          <%- if @new_accounts.any? && @old_accounts.any? -%>
          <li class="existing_account_label">
            <%- if @old_accounts.size == 1 -%>
            <br/>
            &hellip;and this existing account:
            <%- else -%>
            <br/>
            &hellip;and these existing accounts:
            <%- end # if @old_accounts.size == 1 -%>
          </li>
          <%- end -%>

          <%- @old_accounts.each do |account| -%>
          <li class="existing_account">
            <%= hidden_field "accounts[#{account.to_param}][enabled]", "1" %>
            <span class="check_box" <%- unless @new_accounts.any? -%>style="visibility:hidden"<%- end -%>>
              <input type="checkbox" checked="checked" disabled="disabled" /></span>
            <%= text_field_tag "accounts[#{account.to_param}][name]", account.name, :class => "medium_text_field account_name" %>
            <input type="text" class="medium_text_field balance disabled" disabled="disabled" value="<%=h number_to_currency(account.balance, :unit => account.currency.unit) %>" />
          </li>
          <%- end -%>
        </ul><!-- END bank_accounts -->

              <!-- <a class="button submit green"><span>Add Another Bank</span></a> -->
              <a class="button submit green"><span style="width:80px; min-width:80px; text-align:center;">Save</span></a>
              <%- end -%>
            </div><!-- END form_body -->

            <script type="text/javascript" charset="utf-8">
            $(function() {
            $('.account_name').focus();
            });
            </script>

            <div class="clear">&nbsp;</div>
          </div><!-- END color_body -->

          <div class="clear">&nbsp;</div>
        </div><!-- END upload index -->
      </div>
    </div></div>
    <div class="bottom"><div class="right"></div></div>
  </div>
</div>