config/routes.rb
Pfc::Application.routes.draw do
  ## Dashboard

  root :to => 'dashboard#index'
  get 'dashboard' => redirect('/'), :as => 'dashboard'

  ## Login & Signup

  get  'login'  => 'sessions#new',     :as => 'login'
  post 'login'  => 'sessions#create'
  get  'logout' => 'sessions#destroy', :as => 'logout'

  resource :session

  get  'signup' => 'users#new', :as => 'signup'
  post 'signup' => 'users#create'

  ## Accounts, Transactions, Analytics, & Uploads

  resources :accounts do
    resources :transactions, :controller => 'txactions' do
      member do
        put :undelete
      end
    end

    collection do
      get  :search
      post :enable
      post :trigger_updates
    end

    member do
      get :financial_institution_site
    end
  end

  # TODO: Fix this hack.
  get '/transactions/rational(.:format)' => 'rational_txactions#index'
  get '/transactions/rational/*tags(.:format)', :to => 'rational_txactions#index'

  resources :transactions, :controller => 'txactions' do
    member do
      put :undelete
      get :on_select_merchant
      get :transfer_selector
      get :merchant_list_checks
    end
  end

  resources :tags
  resources :attachments
  resources :account_merchant_tag_stats
  resources :targets
  resources :trends
  resources :uploads do
    collection do
      match :choose
      get   :manual
    end
  end

  # TODO: use resource routing for this
  post '/targets/delete' => 'targets#destroy'

  resources :merchants do
    collection do
      get :my,     :to => 'merchants#user_index'
      get :public, :to => 'merchants#public_index'
    end
  end

  resources :financial_insts, :path => 'financial-institutions'

  ## Member Data Snapshots

  resource  :snapshot

  ## Big Rock Candy Mountain Passthrough

  match '/data/transactions/*uri(.:format)',            :to => 'brcm#transactions'
  match '/data/investment-transactions/*uri(.:format)', :to => 'brcm#transactions'
  match '/data/*uri(.:format)',                         :to => 'brcm#passthrough'

  ## User Profile & Preferences

  resource :profile
  resource :preferences, :controller => 'user_preferences'
  resource :user do
    post :edit_filter_tags, :to => 'users#edit_filter_tags'
    get :password, :to => 'users#edit_password'
    put :password, :to => 'users#update_password'
    get :download_data
    get :delete_membership
  end

  ## Server-Side Uploader

  resources :credentials, :controller => 'account_creds' do
    resources :jobs, :controller => 'ssu_jobs'
  end

  ## Help & About

  get 'page/contribute', :as => :contribute, :to => 'page#contribute'
  get 'page/what',       :as => :what,       :to => 'page#what'
end

app/models/account.rb
class Account < ActiveRecord::Base
  concerned_with :uploads
  concerned_with :sample
  concerned_with :status

  scope :visible, :conditions => {:status => Status::VISIBLE}
  scope :for_user, lambda {|user| {:conditions => {:account_key => user.account_key}} }

  belongs_to :user, :foreign_key => 'account_key', :primary_key => 'account_key'
  belongs_to :financial_inst
  belongs_to :account_cred

  has_many :txactions,
           :include => [:merchant, :taggings, :txaction_type, :account],
           :conditions => ["txactions.status = ?", Txaction::Status::ACTIVE],
           :order => 'date_posted desc, sequence, txactions.created_at desc'
  # REVIEW: not sure if there's a better name, but the above txactions association
  # loads the merchant, taggings, txaction_type, and account, and there are times where that's not needed
  has_many :simple_txactions,
           :class_name => "Txaction",
           :conditions => ["txactions.status = ?", Txaction::Status::ACTIVE],
           :order => 'date_posted desc, sequence, txactions.created_at desc'
  has_many :all_txactions,
           :class_name => "Txaction",
           :dependent => :destroy
  has_many :account_balances,
           :order => 'balance_date desc',
           :conditions => ['account_balances.status = ?', Constants::Status::ACTIVE],
           :dependent => :destroy
  has_one :last_balance,
          :class_name => 'AccountBalance',
          :order => 'account_balances.balance_date desc, account_balances.created_at desc',
          :conditions => ['account_balances.status = ?', Constants::Status::ACTIVE]

  attr_accessor :untagged_amount
  attr_accessor :newly_created  # used by ofx2importer

  attr_protected :id_for_user, :guid

  before_create :generate_guid
  before_validation :generate_id_for_user, :on => :create
  before_validation :generate_name, :on => :create
  before_create :truncate_account_number
  before_validation :fix_id_for_user

  validates_uniqueness_of :id_for_user, :scope => :account_key
  validates_presence_of :name
  validate :currency_is_not_blank_or_yaml

  URI_PATTERN = %r{^/accounts/(\d+)$}

  #---------------------------------------------------------------------------
  # public class methods
  #

  def self.find_or_create(account)
    if existing_account = find(:first, :order => "status ASC",
      :conditions => ["account_key = ? and account_number = ? and account_type_id = ? \
                       and status != ? and financial_inst_id = ?",
                       account.account_key, last4(account.account_number), account.account_type_id,
                       Constants::Status::DELETED, account.financial_inst_id])
      return existing_account
    else
      # FIXME: this is to try to debug "Validation failed" exceptions
      account.save
      raise "Generate name didn't work: #{account.inspect}" if account.new_record?
      return account
    end
  end

  # find account by account number. just match on last 4 digits
  def self.find_account(user, account_number, account_type, financial_inst_id)
    for_user(user).
      where(:account_number => account_number,
            :account_type_id => account_type.id,
            :financial_inst_id => financial_inst_id).
      visible.
      first
  end

  # find account by account number hash
  def self.find_account_by_account_number_hash(user, account_number_hash, account_type, financial_inst_id)
    for_user(user).
      where(:account_number_hash => account_number_hash,
            :account_type_id => account_type.id,
            :financial_inst_id => financial_inst_id).
      visible.
      first
  end

  def self.find_by_uri(uri)
    find_by_id_for_user(uri[%r{^/accounts/([^/]+)$}, 1]) if uri
  end

  # merge two accounts into a third account, setting the status of the old ones to deleted
  # we create a third account so we can easily undo if necessary
  # if transactions overlap, we keep the merchant_id of the destination account transaction,
  # and merge the one-time tags of both transactions
  def self.merge(from_account, to_account)
    new_account = nil
    Account.transaction do
      # create duplicate of to account as new_account
      new_account = Account.create!(to_account.attributes)
      to_account.txactions.each do |t|
        # update wesabe_txid with the account #
        t.wesabe_txid.gsub!(/^\d+/,new_account.id.to_s) if t.wesabe_txid
        t.account = new_account
        new_txaction = Txaction.new(t.attributes)
        new_txaction.bulk_update_save!
        if t.taggings.any?
          TxactionTagging.update_all(["txaction_id = ?", new_txaction.id], ["txaction_id = ?", t.id])
        end
      end
      # merge account balances and uploads
      AccountBalance.update_all(["account_id = ?", new_account.id], ["account_id in (?)", [to_account.id, from_account.id]])
      AccountUpload.update_all(["account_id = ?", new_account.id], ["account_id in (?)", [to_account.id, from_account.id]])

      # create a lookup hash of wesabe_txids in the new account (replace the account number in the beginning with
      # that of the from account, since we're going to be looking up those txactions)
      unless to_account.manual_account?
        new_ids_array = new_account.txactions.map do |t|
          [t.wesabe_txid.gsub(/^\d+/,from_account.id.to_s), t]
        end.flatten
        new_wesabe_txids = Hash[*new_ids_array]
      end

      from_account.txactions.each do |t|
        if new_wesabe_txids && new_wesabe_txids[t.wesabe_txid]
          # txaction exists in destination account, so merge tags
          new_txaction = new_wesabe_txids[t.wesabe_txid]
          new_txaction.add_tags(t.tags)
        else
          # fix the wesabe_txid
          t.wesabe_txid.gsub!(/^\d+/, new_account.id.to_s) if t.wesabe_txid
          t.account = new_account
          new_txaction = Txaction.new(t.attributes)
          new_txaction.bulk_update_save!
          if t.taggings.any?
            TxactionTagging.update_all(["txaction_id = ?", new_txaction.id], ["txaction_id = ?", t.id])
          end
        end
      end

      # set status of from_ and to_accounts to deleted
      from_account.safe_delete
      to_account.safe_delete
    end
    # run final calculations on the new account
    new_account.reload # make sure the various associations are reloaded
    new_account.calculate!
    return new_account
  end

  # Return last 4 word characters of account number.
  # If a regex is provided, use that to find the "last 4" digits. Up to 6 characters
  # (the size of the accounts.account_number column) can be stored if a regex is provided
  def self.last4(acct_number, regex = nil)
    acct_number = acct_number.to_s.gsub(/\W/,'') # always strip non-word characters
    if regex.present? && m = acct_number.match(/#{regex}/)
      # if the regex doesn't specify any groupings, this is bad, so best to just explode
      if m.length < 2
        raise ArgumentError, "Regex provided, but no groupings specified"
      end

      return m[1..-1].join.last(6) # concatenate all captured groups
    else
      return acct_number.last(4)
    end
  end

  #---------------------------------------------------------------------------
  # public instance methods
  #

  def destroy_deferred
    safe_delete
    Resque.enqueue(DestroyAccount, self.id)
  end

  # override destroy method to set the status to DISABLED if this is an SSU account; otherwise, delete it outright
  def destroy
    _run_destroy_callbacks do
      if new_record? || !ssu?
        super
      elsif account_cred.accounts.count == 1
        super.tap do # delete ourselves first to avoid a loop -- destroying the cred will also destroy any disabled accounts
          account_cred.destroy
        end
      else
        self.class.update_all(["status = ?", Constants::Status::DISABLED], ["id = ?", id])
        false # stop the callback chain
      end
    end
  end

  # set the status of this account and all its txactions to DELETED
  def safe_delete
    update_attribute(:status, Constants::Status::DELETED)
    Txaction.safe_delete(all_txactions)
  end

  # override AR method so we can return a currency object
  def currency
    currency_name = read_attribute('currency')
    Currency.new(currency_name) if currency_name
  end

  def uri
    "/accounts/#{id_for_user}"
  end

  # override AR method so we can set with a Currency object
  def currency=(cur)
    if cur
      write_attribute(:currency, cur.to_s)
    else
      write_attribute(:currency, nil)
    end
  end

  # account type is no longer an AR model, so return account_type the old fashioned way
  def account_type
    AccountType.find(account_type_id)
  end

  def account_type=(obj)
    if obj.is_a?(AccountType)
      self.account_type_id = obj.id
    else
      raise ActiveRecord::AssociationTypeMismatch.new("AccountType expected, got #{obj.class}")
    end
  end

  # return the name of the FI associated with this account, if any. This is a convenience method for
  # financial_inst.name, since some account types (just cash accounts right now) don't have an FI
  def financial_inst_name
    financial_inst.name if financial_inst
  end

  def wesabe_id
    financial_inst.wesabe_id if financial_inst
  end

  def new_txaction
    Txaction.new(:account => self, :status => Constants::Status::ACTIVE)
  end

  # return the current balance for this account
  def balance
    return nil unless has_balance?

    return calculate_balance
  end

  def calculate_balance
    return nil unless has_balance?

    if manual_account? && (most_recent = simple_txactions.first)
      # manual accounts differ in that the last_balance is probably not the balance as of the most recent
      # transaction, so calculate the balance of the most recent txaction
      new_balance = most_recent.calculate_balance!
    else
      last_bal = last_balance(true) # make sure we get the uncached last_balance
      new_balance = (last_bal && last_bal.balance) || 0
    end

    return new_balance
  end

app/models/account/destroy_account.rb
class Account::DestroyAccount
  @queue = :normal

  def self.perform(id)
    account = Account.find_by_id(id)
    return if account.nil?

    User.with_current_user(account.user) do
      account.destroy
    end
  end
end

app/models/account/sample_concern.rb
class Account
  def self.create_sample(attrs={})
    Account.create(attrs.reverse_merge(
      :name => "Sample Account",
      :currency => 'USD',
      :account_type_id => AccountType::CHECKING,
      :balance => rand(2000) - 1000
    ))
  end
end

app/models/account/status_concern.rb
class Account
  module Status
    def self.string_for(code)
      constants.each do |const|
        return const.capitalize if const_get(const) == code
      end

      return string_for(DEFAULT)
    end

    def self.for_string(string)
      constants.each do |const|
        return const_get(const) if const.downcase == string.downcase
      end

      return DEFAULT
    end

    ACTIVE     = 0
    DELETED    = 1
    ARCHIVED   = 3
    DISABLED   = 5

    DEFAULT    = ACTIVE
    VISIBLE    = [ACTIVE, ARCHIVED]
  end

  MAX_ATTACHMENTS = 5

  def visible?
    VISIBLE_STATUSES.include?(status)
  end

  def active?
    status == Status::ACTIVE
  end

  def active!
    update_attribute :status, Status::ACTIVE
  end

  def deleted?
    status == Status::DELETED
  end

  def deleted!
    update_attribute :status, Status::DELETED
  end

  def archived?
    status == Status::ARCHIVED
  end

  def archived!
    update_attribute :status, Status::ARCHIVED
  end

  def disabled?
    status == Status::DISABLED
  end

  def disabled!
    update_attribute :status, Status::DISABLED
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :check_authentication

  # GET /accounts
  def index
    respond_to do |format|
      format.html
    end
  end

  # GET /accounts/1
  def show
    if account.nil?
      redirect_to accounts_url
    else
      render :action => 'index'
    end
  end

  # GET /accounts/search
  def search
    render :action => 'index'
  end

  # DELETE /accounts/1
  def destroy
    if account.nil?
      return render :text => "Could not delete your account.", :status => :not_found
    end

    @account.destroy_deferred
    render :nothing => true, :status => :accepted
  end

  # GET /accounts/1/financial_institution_site
  def financial_institution_site
    if account && account.financial_inst && account.financial_inst.url.present?
      redirect_to account.financial_inst.url
    else
      render :nothing => true, :status => :not_found
    end
  end

  # POST /accounts
  def create
    # default to USD if the currency is missing or unknown
    params[:currency] = 'USD' if !Currency.known?(params[:currency])
    @account = Account.create(:name => params[:name],
                              :user => current_user,
                              :account_type_id => params[:balance] ? AccountType::MANUAL : AccountType::CASH,
                              :currency => params[:currency])
    @account.balance = params[:balance] if params[:balance]

    respond_to do |format|
      format.html { redirect_to account_url(@account) }
      format.json do
        if @account.errors.any?
          render(:json => {:errors => @account.errors.full_messages.to_json}, :status => :bad_request)
        else
          render(:json => {:id => @account.id_for_user, :guid => @account.guid }, :status => :ok)
        end
      end
    end
  end

  # POST /accounts/trigger_updates
  def trigger_updates
    User::AccountUpdateManager.login!(current_user, self, :force => true)
    render :nothing => true
  end

  # POST /accounts/enable
  def enable
    params[:accounts] && params[:accounts].each do |id, input|
      account = current_user.account_by_id_for_user(id)
      account.name = input[:name]
      if input[:enabled]
        account.status = Constants::Status::ACTIVE
        account.save
      else
        account.destroy # set status to DISABLED and delete txactions
      end
    end
    redirect_to(params[:add_another] ? new_upload_path : user_home_path)
  end

private

  def account
    # if the id looks like a guid, do the look up by that
    @account ||= (params[:id] =~ /^[0-9a-z]{64}$/) ?
      current_user.accounts.find_by_guid(params[:id]) :
      current_user.accounts.find_by_id_for_user(params[:id])
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def security_with_linked_ticker(security)
    str = security.to_s
    if !(security.ticker.blank? || security.ticker =~ /\d/)
      str += (" (%s)" % link_to(security.ticker, "http://finance.google.com/finance?q=#{security.ticker}", :target => "_new"))
    end
    return str
  end

  # helper so we can optionally display the investment memo
  # if there's no security, or the memo is the same as the security name, don't display the memo
  def investment_memo(txaction)
    # eww
    if txaction.memo &&
        txaction.investment_security &&
        txaction.investment_security.name &&
        (txaction.memo.gsub(/\s/,'') != txaction.investment_security.name.gsub(/\s/,''))
      txaction.memo
    end
  end
end

app/views/accounts/_export.html.erb
<div id="export">
   <a id="export-link" class="select"></a>
   <a class="export-text">Export transactions:</a>
   <div id="export-dialog" class="edit-dialog bottom-ralign" style="display:none">
     <div class="top"><div class="right">
       <p class="export-details">Export transactions from <strong><span id="export-source">All Accounts</span></strong></p>
       <label>Date Range:</label>
       <select id="date-range-select" name="date-range-select">
         <option value="all">All</option>
         <option value="tax">Tax Year <%= Time.now.year - 1 %></option>
         <option value="ytd">Year-to-date</option>
         <option value="custom">Custom</option>
       </select>
       <div id="custom-date-range" style="display:none">
         <div class="notification error" style="display:none">
           <div class="top"><div class="right">
             <p class="message small start-date-error" style="display:none"></p>
             <p class="message small end-date-error" style="display:none"></p>
           </div></div>
           <div class="bottom"><div class="right"></div></div>
         </div>
         <div class="date-range">
           <label>Starting:</label>
           <input type="text" id="start-date" name="start-date"/>
         </div>
         <div class="date-range">
           <label>Ending:</label>
           <input type="text" id="end-date" name="end-date"/>
         </div>
       </div>
       <label>Format:</label>
       <select id="export-format" name="export-format">
         <option value="csv">CSV</option>
         <option value="xls">Excel</option>
         <option value="json">JSON</option>
         <option value="xml">XML</option>
       </select>
     </div></div>
     <div class="bottom"><div class="right">
       <a class="button green confirm save"><span>Export</span></a>
       <a class="button gry cancel"><span>Cancel</span></a>
     </div></div>
   </div>
</div>

app/views/accounts/_investment_header.html.erb
<div id="investment-header" style="display:none">
  <table id="investment-positions">
    <tr class="title"><td colspan="4">Positions</td></tr>
    <tr class="header"><th>Security</th><th class="amount">Units</th><th class="amount">Unit Price</th><th class="amount">Total</th></tr>
    <tr class="subtotal market-value"><td colspan="3" class="amount">Market Value</td><td id="market-value" class="amount"></td></tr>
    <tr class="subtotal available-cash"><td colspan="3" class="amount">Available Funds</td><td id="available-cash" class="amount"></td></tr>
    <tr class="subtotal account-value"><td colspan="3" class="amount">Account Value</td><td id="account-value" class="amount"></td></tr>
  </table>
</div>

app/views/accounts/_transactions_chart.html.erb
<div id="control-panel" style="display:none">
  <div id="activity">
    <p class="small">Transaction Activity:</p>
    <a class="toggle-button on" id="all-transactions-button" title="Show all transactions"><span>All</span></a>
    <a class="toggle-button" id="unedited-transactions-button" title="Show unedited and untagged transactions"><span>Unedited</span></a>
  </div>
  <div id="date-range" style="margin-left: 121px;">
    <p class="small">View:</p>
    <a class="toggle-button time-0"><span>1m</span></a>
    <a class="toggle-button time-1"><span>3m</span></a>
    <a class="toggle-button time-2"><span>6m</span></a>
    <a class="toggle-button time-3"><span>1y</span></a>
  </div>
  <div id="graphs">
    <p class="small">Graph by:</p>
    <a class="toggle line"></a>
    <a class="toggle vbar"></a>
  </div>
  <div class="clear"></div>
</div>
<div id="charts">
  <%= render :partial => "charts/txn" %>
</div>
<div id="transaction-totals" class="graph-footer" style="display:none">
  <ul>
    <li class="transaction-totals spending">
      <span><div class="spending-dot">&bull;</div>Total Spending<span class="amount">$23.00</span></span></li>
  </ul>
  <ul class="center">
    <li class="transaction-totals earnings"><span><div class="earnings-dot">&bull;</div>Total Earnings<span class="amount">$5.00</span></span></li>
  </ul>
  <ul class="r-align">
    <li class="transaction-totals net-balance"><span><div class="net-balance-dot">&bull;</div>Difference<span class="amount">-$18.00</span></span></li>
  </ul>
  <div class="clear"></div>
</div>

app/views/accounts/_widget.html.erb
<%# requires stylesheet "pages/accounts" %>
<!--[if IE 6]>
    <%= stylesheet_link_tag "ie6" %>
<![endif]-->
<%# requires javascript "views/widgets/accounts" %>

<%# wesabe.views.widgets.accounts.AccountWidget %>
<div class="one-column" id="accounts">
  <div class="top"><div class="right"><div class="grip"></div></div></div>
  <div class="middle"><div class="right">
    <div class="content">
      <div class="module-header">
        <a class="edit-button button gry"><span>Edit</span></a>
        <a class="done-button button green" style="display:none"><span>Done</span></a>
        <div class="update-button button">
          <%= image_tag 'maincontent/animated-gifs/ssu-animated-gif-button.gif', :alt => 'updating', :class => 'updating-spinner' %>
        </div>
        <h5><%= link_to 'My Accounts', accounts_path %></h5>
      </div>
      <%= image_tag 'maincontent/animated-gifs/loading-dots-animated.gif', :class => 'loading-indicator' %>
      <%# wesabe.views.widgets.accounts.AccountGroupList %>
      <ul class="account-groups">
        <%# wesabe.views.widgets.accounts.AccountGroup %>
        <li class="one-col-list group template">
          <span class="view"></span>
          <h6>
            <a>
              <%# wesabe.views.widgets.MoneyLabel %>
              <span class="total"><!-- $6,782.45 --></span>
              <span class="text-content"><!-- Group Name --></span>
            </a>
          </h6>
          <div class="clear"></div>
          <ul>
            <%# wesabe.views.widgets.accounts.Account %>
            <li class="account template">
              <!-- for cash accounts -->
              <div class="account-status cash"></div>

              <!-- for SSU accounts -->
              <div class="account-status update">
                <%= image_tag 'maincontent/animated-gifs/ssu-animated-gif-button.gif', :alt => 'updating', :class => 'updating-spinner' %>
              </div>

              <div class="account-status update error"></div>

              <!-- for manual upload accounts -->
              <div class="account-status upload">
                <div class="hover-box" style="display:none">
                  <div class="top"><div class="right">
                    <div class="header">Manual Update</div>
                    <p>To update your account information, go to <a class="fi-link" target="_blank">your financial institution</a>, and download your statement. Then upload it to Wesabe.<p>
                    <p><strong>Formats supported:</strong> OFX (preferred), QIF, QFX, and OFC</p>
                    <%= form_tag uploads_path, :class => 'account_upload', :multipart => true do %>
                      <input id="statement" type="file" size="20" name="statement" alt="browse"/>
                      <input name="account_uri" type="hidden" value="" />
                      <div class="buttons">
                        <a class="button confirm green"><span>Upload</span></a>
                        <a class="button cancel gry"><span>Cancel</span></a>
                      </div>
                    <% end %>
                    <div class="clear"></div>
                  </div></div>
                  <div class="bottom"><div class="right"></div></div>
                </div>
              </div>
              <!-- for editing an account-->
              <div class="edit-account">
                <div class="edit" style="display:none"></div>
              </div>
              <span class="account-name">
                <span class="balance"><!-- $200.00 --></span>
                <a class="text-content"><!-- My Cash Account --></a>
              </span>
            </li>
          </ul>
        </li>
      </ul>
      <div class="accounts-total">
          <h6><span class="total"><!-- $167,890.00 --></span>Total</h6>
      </div>
      <a href="/uploads/new" class="add-account-button button orange"><span>Add an Account</span></a>
    </div>
  </div></div>
  <div class="bottom"><div class="right"></div></div>
  <%# wesabe.views.widgets.accounts.AccountEditDialog %>
  <div class="edit-dialog">
    <div class="top"><div class="right">
      <div class="edit-details">
        <input type="text" name="account-name">
        <%= select_tag 'account-currency', options_for_select(currency_full_options_for_select) %>
        <div class="current-balance">
          <label>Current Balance:</label>
          <input type="text" name="current-balance">
        </div>
        <div class="edit-dialog-inset">
          <a class="edit-dialog-inset-tab"><span class="ssu">Manage Uploader</span></a>
          <a class="edit-dialog-inset-tab"><span class="track-balance">Track Balance</span></a>
          <a class="edit-dialog-inset-tab on"><span class="archive-account">Archive Details</span></a>
          <div class="top"><div class="right">
            <div class="inset-tab-text ssu">
              <div class="header">You are using the Automatic Uploader</div>
              If the login credentials you use to connect to your bank have changed,
              click <a class="reset-creds">here</a> to reset them.<br/>
              To delete your bank credentials and deactivate the Automatic Uploader, click <a class="delete-creds">here</a>.
            </div>
            <div class="inset-tab-text ssu-error">
              <div class="header">Automatic Uploader Error</div>
              Your bank has reported an error. To reset your bank credentials, click <a class="reset-creds">here</a>.
            </div>
            <div class="inset-tab-text track-balance">
              <input type="checkbox" name="track-balance" id="track-balance">
              <label class="checkbox" for="track-balance">
                <strong>Track Balance:</strong>
                Cash accounts can track their current balance like a checking account would. A balance can be useful if you want to reconcile the cash in your wallet with your recorded transactions.
              </label>
            </div>
            <div class="inset-tab-text archive-account on">
              <input type="checkbox" name="archive-account" id="archive-account">
              <label class="checkbox" for="archive-account">
                <strong>Archive Account:</strong>
                Archived accounts let you keep information from expired or terminated accounts. An archived account preserves your transaction information, but doesn't get included in your account totals.
              </label>
            </div>
          </div></div>
          <div class="bottom"><div class="right"></div></div>
        </div>
      </div>

      <div class="confirmation delete-details">
        <div class="header">Are you sure you want to permanently delete all
          the information in <strong>&lsquo;<span class="account-name-text">
          Account Name</span>&rsquo;</strong>? This cannot be undone.
        </div>
        <p class="error-message"></p>
      </div>

      <p class="error-message">Sorry, there was an error saving your changes.</p>
    </div></div>
    <div class="bottom"><div class="right">
      <img class="spinner" src="/images/activity-indicator.gif">
      <div class="edit-details">
        <a class="button green confirm"><span>Save</span></a>
        <a class="button gry cancel"><span>Cancel</span></a>
        <a class="button delete conf">Delete Account&hellip;</a>
      </div>
      <div class="delete-details">
        <a class="button red delete confirm"><span>Delete</span></a>
        <a class="button gry cancel"><span>Cancel</span></a>
      </div>
    </div></div>
  </div>
</div>

app/views/accounts/index.html.erb
<%= render :file => 'accounts/account-transactions' %>

<script type="text/javascript">
  jQuery(function(){ page = new wesabe.views.pages.accounts() });
</script>

<% preload_accounts; preload_credentials; preload_tags %>